language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy
install:
  - pip install flake8
  - python setup.py install
  - pip list
  - flake8 --version
script:
  - python setup.py test -q
  - flake8 pyflakes setup.py
matrix:
  allow_failures:
    - python: pypy
