language: python
python:
  - 2.5
  - 2.6
  - 2.7
  - pypy
install:
  - python setup.py install
  - pip install unittest2
script:
  - python -m unittest2 discover
matrix:
  allow_failures:
    - python: pypy
